Repository jhj0517/Whisper-WebUI, pull requests merged in 2025-01, with the labels that each got.

#441 Use fixed version of `faster-whisper==1.1.1`
  modules/vad/silero_vad.py
  modules/whisper/base_transcription_pipeline.py
  notebook/whisper-webui.ipynb
  requirements.txt
Labels: bug

#450 Fix i18n initialization bug
  app.py
Labels: bug

#457 Fix wrong input for the diarization pipeline
  modules/whisper/base_transcription_pipeline.py
Labels: bug

#458 Set `origin_audio` after bgm removal
  modules/whisper/base_transcription_pipeline.py
Labels: enhancement

#462 Add placeholders for models/outputs dirs
  models/Diarization/diarization_models_will_be_saved_here
  models/NLLB/nllb_models_will_be_saved_here
  models/UVR/uvr_models_will_be_saved_here
  models/Whisper/faster-whisper/faster_whisper_models_will_be_saved_here
  models/Whisper/insanely-fast-whisper/insanely_fast_whisper_models_will_be_saved_here
  models/Whisper/whisper_models_will_be_saved_here
  models/models_will_be_saved_here
  outputs/UVR/instrumental/UVR_outputs_for_instrumental_will_be_saved_here
  outputs/UVR/vocals/UVR_outputs_for_vocals_will_be_saved_here
  outputs/outputs_will_be_saved_here
  outputs/translations/translation_outputs_will_be_saved_here
Labels: bug

#465 Feature to include subdirectory files
  app.py
  modules/whisper/base_transcription_pipeline.py
  tests/test_transcription.py
Labels: enhancement

#467 Add ability to save output as same directory with inputs
  app.py
  configs/default_parameters.yaml
  modules/whisper/base_transcription_pipeline.py
  tests/test_transcription.py
Labels: enhancement

#473 Fix elapsed time
  modules/whisper/base_transcription_pipeline.py
Labels: bug

#477 add option to provide HuggingFace-token via environment variable
  modules/whisper/base_transcription_pipeline.py
Labels: enhancement

#475 Fix total time elapsed does not account for all steps
  modules/whisper/base_transcription_pipeline.py
Labels: enhancement

#476 increase possible file name length for youtube transcriptions
  modules/utils/subtitle_manager.py
Labels: enhancement

#480 Fix audio validation with video file
  modules/utils/audio_manager.py
  modules/whisper/base_transcription_pipeline.py
Labels: bug

#478 Validate segments
  modules/whisper/base_transcription_pipeline.py
Labels: enhancement

#484 fixed transformers version for issue #470
  requirements.txt
Labels: bug, hallucination

#482 add option to unload whisper and diarizer model when done
  backend/configs/config.yaml
  configs/default_parameters.yaml
  configs/translation.yaml
  modules/whisper/base_transcription_pipeline.py
  modules/whisper/data_classes.py
Labels: enhancement
