Repository jhj0517/Whisper-WebUI, pull requests merged in 2025-08, with the labels that each got.

#580 Set `word_timestamps` to always True
  modules/whisper/faster_whisper_inference.py
Labels: hallucination

#586 Fix LookupError
  app.py
  notebook/whisper-webui.ipynb
  requirements.txt
Labels: bug

#589 fix: hide language setting by default
  app.py
Labels: enhancement
